trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: 'vsprojects/pcsx-redux.sln'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: 'ps1-packer'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j'

- task: CopyFiles@2
  inputs:
    Contents: |
      src/mips/openbios/openbios.bin
      src/mips/openbios/openbios.elf
    TargetFolder: '$(build.artifactStagingDirectory)/openbios'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j deepclean'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j BOOT=cart PACK_SHELL=true'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mv src/mips/openbios/openbios.bin src/mips/openbios/openbios-cart.rom
      mv src/mips/openbios/openbios.elf src/mips/openbios/openbios-cart.elf

- task: CopyFiles@2
  inputs:
    Contents: |
      src/mips/openbios/openbios-cart.rom
      src/mips/openbios/openbios-cart.elf
    TargetFolder: '$(build.artifactStagingDirectory)/openbios'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j deepclean'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      wget https://github.com/JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1/releases/download/8.0.J/UNIROM_BOOTDISC_8.0.J.zip

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'UNIROM_BOOTDISC_8.0.J.zip'
    destinationFolder: 'unirom'
    cleanDestinationFolder: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ./ps1-packer unirom/stuff/unirom_b.exe -o unirom_packed.exe

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j FASTBOOT=true EMBED_PSEXE=../../../unirom_packed.exe'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mv src/mips/openbios/openbios.bin src/mips/openbios/openbios-unirom.bin
      mv src/mips/openbios/openbios.elf src/mips/openbios/openbios-unirom.elf

- task: CopyFiles@2
  inputs:
    Contents: |
      src/mips/openbios/openbios-unirom.bin
      src/mips/openbios/openbios-unirom.elf
    TargetFolder: '$(build.artifactStagingDirectory)/openbios'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j deepclean'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j FASTBOOT=true EMBED_PSEXE=../../../unirom_packed.exe BOOT=cart'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mv src/mips/openbios/openbios.bin src/mips/openbios/openbios-unirom-cart.rom
      mv src/mips/openbios/openbios.elf src/mips/openbios/openbios-unirom-cart.elf

- task: CopyFiles@2
  inputs:
    Contents: |
      src/mips/openbios/openbios-unirom-cart.rom
      src/mips/openbios/openbios-unirom-cart.elf
    TargetFolder: '$(build.artifactStagingDirectory)/openbios'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j deepclean'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j FASTBOOT=true'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mv src/mips/openbios/openbios.bin src/mips/openbios/openbios-fastboot.bin
      mv src/mips/openbios/openbios.elf src/mips/openbios/openbios-fastboot.elf

- task: CopyFiles@2
  inputs:
    Contents: |
      src/mips/openbios/openbios-fastboot.bin
      src/mips/openbios/openbios-fastboot.elf
    TargetFolder: '$(build.artifactStagingDirectory)/openbios'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j deepclean'

- task: Bash@3
  inputs:
    filePath: 'dockermake.sh'
    arguments: '-C src/mips/openbios -j FASTBOOT=true BOOT=cart'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mv src/mips/openbios/openbios.bin src/mips/openbios/openbios-fastboot-cart.rom
      mv src/mips/openbios/openbios.elf src/mips/openbios/openbios-fastboot-cart.elf

- task: CopyFiles@2
  inputs:
    Contents: |
      src/mips/openbios/openbios-fastboot-cart.rom
      src/mips/openbios/openbios-fastboot-cart.elf
    TargetFolder: '$(build.artifactStagingDirectory)/openbios'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'bios'
    publishLocation: 'Container'
