name: Linux CI AUR

on:
  push:
    branches:
      - main
      - aur-package-ci
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install dependencies
        run: | 
          pacman -Syu --noconfirm --needed capstone curl ffmpeg freetype2 glfw libuv sdl2 zlib git make pkg-config sudo
      - name: Create builduser
        run: |
          useradd builduser -m
          passwd -d builduser
      - name: Build AUR Package
        run: |
          git clone https://aur.archlinux.org/pcsx-redux-git.git
          chown -R builduser:builduser pcsx-redux-git
          cd pcsx-redux-git
          sudo -u builduser makepkg
